Vagrant.configure(2) do |config|
  config.vm.network 'forwarded_port', guest: 8361, host: 8361
  config.vm.network 'forwarded_port', guest: 80, host: 8080

  config.vm.provision 'shell', inline: '/var/lib/cyclid/client-config.sh'
end 
