Vagrant.configure(2) do |config|
  # Inherited from the Ubuntu-Xenial box
  config.ssh.username = "ubuntu"

  # Make the API & UI accessable
  config.vm.network 'forwarded_port', guest: 8361, host: 8361
  config.vm.network 'forwarded_port', guest: 80, host: 8080

  # Generate the client configuration
  config.vm.provision 'shell', inline: '/var/lib/cyclid/client-config.sh'
end 
